[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_voting = "3HemPUH44fCQf5MN36P4sRg2FSZiY7uQeAgKL8TVCv9x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
